### ISSUE TITLE
[Refactor] DB ERD Refactoring

### ISSUE THREAD

**Issue by kingseungwooya** [CNU-Software-Academy/cheerdo-server#34]
## Issue ( 해결해야할 문제가 무엇인가 ? )
습관 진행도와 캘린더에 매일 성공률를 구하는데 문제가 생김 DB 튜닝이 필요함 
- date로 검색 요건이 많고 calender 습관 진행도 조회시 매 todo에 대해 select하고 count해서 성공률을 계산해야함
- 습관에 대해서 설정시 주기적으로 자동 생성되야함 
- 습관 진행도를 확인하기 위해서 todo table에 자동으로 추가되서 연산 되어야함
## ToDoList ( 해결 하기 위해 해야할 것 )
- ERD Refactoring
![image](https://user-images.githubusercontent.com/86772586/218986139-00b1585b-fdfa-4c97-bc9b-5ddb9602b321.png)
- Calender table추가

**Comment by Im-younique** [comment]
아니면 다른 방안을 모색해볼 수도 있을 것 같습니다.

습관은 member 내에 habit_percent가 있는데 이것을 매일마다 올려주는 역할을 합니다 (물론 습관을 모두 진행하였을 때)
00시 쯤 습관중에 하나라도 진행이 되어 있지 않으면 habit_percent는 0으로 초기화됩니다.

이 후 TODO에 대해서는 매일 달성률을 계산하는데 TODO가 추가 및 완료처리 됐을 때 계산을 계속 해서 넣어주는 방식을 생각할 수 있습니다.
